#
# buildspec.yml
#

version: 0.2

env:
  variables:
    deploy_bucket: newspaper-db-deployable

phases:
  install:
    runtime-versions:
      golang: 1.x
#    commands:

  pre_build:
    commands:
      - BUILD_VERSION=$(date --date="@$(echo ${CODEBUILD_START_TIME} | cut -c1-10)" +"%Y%m%d%H%M%S")
      - COMMIT_TAG=gitcommit-${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - apt install make gcc sqlite3

  build:
    commands:
      #
      # build the assets
      #
      - cd ${CODEBUILD_SRC_DIR}
      - make linux
      #
      # copy to the results bucket
      #
      #
      - aws s3 cp ${CODEBUILD_SRC_DIR}/deployment.zip s3://${deploy_bucket}/${BUILD_VERSION}/deployment.zip --quiet
      #
      # create the git commit tag file
      #
      - touch ${CODEBUILD_SRC_DIR}/${COMMIT_TAG}.git
      - aws s3 cp ${CODEBUILD_SRC_DIR}/${COMMIT_TAG}.git s3://${deploy_bucket}/${BUILD_VERSION}/${COMMIT_TAG}.git --quiet
      #
      # make the latest folder
      #
      - aws s3 sync s3://${deploy_bucket}/${BUILD_VERSION} s3://${deploy_bucket}/latest --delete --quiet

#  post_build:
#    commands:

#
# end of file
#
